### ISSUE TITLE
Enlace a sitio de investigación más destacado

### ISSUE THREAD

**Issue by martinszy** [YoQuieroSaber/votai-theme#10]
El texto "colaborá con nuestra investigación colectiva" debe ser un enlace a http://investigacion.yoquierosaber.org y debe ser un botón más prominente, no debe estar asociado con el texto de arriba.

**Comment by natalibogarin** [comment]
![image](https://cloud.githubusercontent.com/assets/3978642/8867592/c66fa146-31a1-11e5-90db-3187a19b9c9d.png)

Podría ser algo así?
