### ISSUE TITLE
Error al acceder a flatpages

### ISSUE THREAD

**Issue by martinszy** [YoQuieroSaber/votai-theme#13]
Creé una nueva página para la sección "nosotros" y no aparece el enlace en el sitio, ni es accesible.

Error en esta página: http://elecciones2015.yoquierosaber.org/nosotros/

Aquí la págna en la sección de administración:
http://elecciones2015.yoquierosaber.org/admin/flatpages/flatpage/1/

**Comment by lfalvarez** [comment]
Sorry creo que no es obvio -> http://elecciones2015.yoquierosaber.org/pages/nosotros/

**Comment by martinszy** [comment]
Genial!
Y se puede agregar un enlace a eso desde el template?

2015-07-01 10:04 GMT-03:00 Luis Felipe Álvarez Burgos <
notifications@github.com>:

> Sorry creo que no es obvio ->
> http://elecciones2015.yoquierosaber.org/pages/nosotros/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/YoQuieroSaber/votai-theme/issues/13#issuecomment-117656788
> .

## 

_Martín Szyszlican_
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by lfalvarez** [comment]
Acá! `{% get_flatpages '/about/' as about_pages %}`  Creo que esto te podría ayudar también.

[Flatpages documentación](https://docs.djangoproject.com/en/1.8/ref/contrib/flatpages/#limiting-flatpages-by-base-url)
Saludos
