### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by martinszy** [YoQuieroSaber/votai-theme#2]
Debe ser una imágen de 64x64px
Debe contener sólo el isotipo.

**Comment by martinszy** [comment]
Pueden usar este: http://argentina.ynr.staging.mysociety.org/static/img/favicon.6fb2111c9430.ico
http://argentina.ynr.staging.mysociety.org/static/img/apple-touch-icon.976c73215044.png

```
<link rel="shortcut icon" href="/static/img/favicon.6fb2111c9430.ico"/>
<link rel="apple-touch-icon-precomposed" href="/static/img/apple-touch-icon.976c73215044.png"/>
```

**Comment by jpamato** [comment]
ok, gracias!
