### ISSUE TITLE
Hacer documentación del theme

### ISSUE THREAD

**Issue by martinszy** [YoQuieroSaber/votai-theme#40]
El link que esta en el readme para la documentación lleva a un 404 de votai-theme (https://votai-theme.readthedocs.org/en/latest/), por favor arreglen eso para que lleve a un link actual, entiendo que es un problema del repo de votai-theme, pero en su readme tiene que existir una documentación, por ahí contactando al autor de votai-theme?

**Comment by lfalvarez** [comment]
@martinszy me ayudarías a escribir un poco de documentación? a mi me cuesta mucho :disappointed:

**Comment by lfalvarez** [comment]
Necesito que se solucione este issue primero -> rtfd/readthedocs.org#1533

**Comment by martinszy** [comment]
Si, cuenta con eso, tenemos dos semanas a partir de ahora para hacer algo decente.
Tiene que explicar cómo funciona la dependencia de vota inteligente, cómo instalar y editar el tema y los comandos principales de management.

**Comment by lfalvarez** [comment]
Perfecto!

2015-08-03 12:07 GMT-03:00 Martín Szyszlican notifications@github.com:

**Comment by martinszy** [comment]
Ya agregué algo, lo está revisando @sebazelonka
