### ISSUE TITLE
No se ven los colores en las caras del questionary

### ISSUE THREAD

**Issue by martinszy** [YoQuieroSaber/votai-theme#43]
http://beta.yoquierosaber.org/election/pre-candidato-a-presidente/questionary

Aunque el código lo incluye: 

``` pyhon
                                    {% with candidate=taken_position.person %}
                                        {% if candidate.image %}
                                            {% thumbnail candidate.image "50x50" crop="center"  format="PNG" as im %}
                                            <a href="{% url 'candidate_detail_view' election_slug=election.slug slug=candidate.id %}"><img src="{{im.url}}" height="50" width="50" alt="{{candidate.name}}" border="0" class="img-responsive" title="{{candidate.name}}" style="background-color: {{candidate.extra_info.color}} "></a>
                                            {% endthumbnail %}
                                        {% else %}
                                            {% thumbnail candidate.image "50x50" crop="center"  format="PNG" as im %}
                                            <a href="{% url 'candidate_detail_view' election_slug=election.slug slug=candidate.id %}"><img src="{{im.url}}"  height="50" width="50" alt="{{candidate.name}}" border="0" class="img-responsive" title="{{candidate.name}}" style="background-color: {{candidate.extra_info.color}} "></a>
                                            {% endthumbnail %}
                                        {% endif %}
                                        <span>{{candidate.name}}</span>
                                    {% endwith %}
```

https://github.com/YoQuieroSaber/votai-theme/blob/master/votai_theme/templates/elections/election_questionary.html

**Comment by lfalvarez** [comment]
Ya lo tengo! el problema es que la variable `candidate` es de tipo [`Person`](https://github.com/openpolis/django-popolo/blob/master/popolo/models.py#L18-L94) y no de tipo [`Candidate`](https://github.com/ciudadanointeligente/votainteligente-portal-electoral/blob/master/elections/models.py#L30-L52). Pero lo puedo solucionar mediante hacer un template tag que devuelva el diccionario extra_info. Qué tal se ve esa solución?

**Comment by martinszy** [comment]
Si, me parece bien!

2015-08-03 16:34 GMT-03:00 Luis Felipe Álvarez Burgos <
notifications@github.com>:

> Reopened #43 https://github.com/YoQuieroSaber/votai-theme/issues/43.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/YoQuieroSaber/votai-theme/issues/43#event-372358174.

## 

_Martín Szyszlican_
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by lfalvarez** [comment]
Revisate este PR #44
